// export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST"
// export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS"
// export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE"

export const FILMS_REQUEST = "FILMS_REQUEST";
export const FILMS_SUCCESS = "FILMS_SUCCESS";
export const FILMS_FAILURE = "FILMS_FAILURE";
export const NAME_SORT = "NAME_SORT";
export const REPLACE_FILMS = "REPLACE_FILMS";
